### ISSUE TITLE
Ridge.ridge outputs weights for first target only

### ISSUE THREAD

**Issue by drorcohengithub** [alexhuth/ridge#4]
Hi Alex,

Thanks for the awesome resource. I think there is a small issue with the ridge function - it only outputs the weight for the first target, the rest are zero. See example below:
.................................
import numpy as np
import logging
from ridge import ridge, ridge_corr, bootstrap_ridge

logging.basicConfig(level=logging.DEBUG)

#Create some test data
N = 200 #features
M = 1000 #response sources (voxels, whatever)
TR = 1000 #regression timepoints
TP = 200 #prediction timepoints

snrs = np.linspace(0, 0.2, M)
realwt = np.random.randn(N, M)
features = np.random.randn(TR+TP, N)
realresponses = np.dot(features, realwt) # shape (TR+TP, M)
noise = np.random.randn(TR+TP, M)
responses = (realresponses * snrs) + noise

Rresp = responses[:TR]
Presp = responses[TR:]
Rstim = features[:TR]
Pstim = features[TR:]

##Run bootstrap ridge
#wt, corr, valphas, bscorrs, valinds = bootstrap_ridge(Rstim, Rresp, Pstim, Presp,
#t                                                       alphas=np.logspace(-2, 2, 20),
#t                                                       nboots=5,
#t                                                       chunklen=10, nchunks=15)

wt = ridge.ridge(Rstim, Rresp,0)

#inspect a few features for first and second target
print (wt[0:5,0:2])

.......................
Output:

[[ 0.04861679  0.        ]
 [-0.00615976  0.        ]
 [-0.06589772  0.        ]
 [ 0.00239068  0.        ]
 [-0.00290565  0.        ]]

.......................
I'm guessing the issue is with this loop (lines 54-61) , which mixes the multiple targets and alphas:

#Compute weights for each alpha
    ualphas = np.unique(nalphas)
    wt = np.zeros((stim.shape[1], resp.shape[1]))
    for ua in ualphas:
        selvox = np.nonzero(nalphas==ua)[0]
        #awt = reduce(np.dot, [Vh.T, np.diag(S/(S**2+ua**2)), UR[:,selvox]])
        awt = Vh.T.dot(np.diag(S/(S**2+ua**2))).dot(UR[:,selvox])
        wt[:,selvox] = awt   

.......................
Cheers!
Dror (now at Shinji Nishimoto's lab at NICT)

**Comment by alexhuth** [comment]
Hey Dror -- thanks for pointing this out! The issue appeared when supplying a single integer-valued alpha, which was not detected as a float, and thus wasn't expanded to an array (see https://github.com/alexhuth/ridge/blob/master/ridge.py#L44). I just pushed a small fix that should address this specific problem, but there should probably be more rigorous checking of parameters in these functions :)
